from enum import StrEnum
from typing import Optional

from pydantic import BaseModel


class ErrorCode(StrEnum):
    BAD_REQUEST = "BAD_REQUEST"
    VALIDATION_ERROR = "VALIDATION_ERROR"  # Validasi data request salah
    AUTH_REQUIRED = "AUTH_REQUIRED"  # Token tidak ditemukan
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_EMPLOYEE_ID_EXISTS = "USER_EMPLOYEE_ID_EXISTS"
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"
    FORBIDDEN = "FORBIDDEN"  # Role tidak cukup
    NOT_FOUND = "NOT_FOUND"  # Data tidak ditemukan
    INTEGRATION_ERROR = "INTEGRATION_ERROR"  # Error komunikasi dengan Odoo
    SERVER_ERROR = "SERVER_ERROR"  # Unexpected
    USER_ALREADY_ASSIGNED = "USER_ALREADY_ASSIGNED"
    MANAGE_USER_NOT_FOUND = "MANAGE_USER_NOT_FOUND"
    ITEM_ALREADY_EXISTS = "ITEM_ALREADY_EXISTS"
    DEPARTMENT_NOT_FOUND = "DEPARTMENT_NOT_FOUND"
    BRANCH_NOT_FOUND = "BRANCH_NOT_FOUND"
    DATABASE_ERROR = "DATABASE_ERROR"
    USER_ALREDY_ACTIVED = "USER_ALREDY_ACTIVED"
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
    USER_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    MANAGER_ALREADY_EXISTS = "MANAGER_ALREADY_EXISTS"
    BRANCH_REQUIRED_FOR_MANAGER = "BRANCH_REQUIRED_FOR_MANAGER"
    INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"


class ErrorResponse(BaseModel):
    code: ErrorCode
    message: str
    details: Optional[dict] = None
