"""update table quotations

Revision ID: 1e8c6e9686cb
Revises: 687aa1665972
Create Date: 2025-12-12 07:17:28.290909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8c6e9686cb'
down_revision: Union[str, Sequence[str], None] = '687aa1665972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_items', sa.Column('notes', sa.Text(), nullable=False))
    op.alter_column('quotation_items', 'unit_price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('quotation_items', 'subtotal',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('quotations', 'grand_total',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotations', 'grand_total',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('quotation_items', 'subtotal',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('quotation_items', 'unit_price',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('quotation_items', 'notes')
    # ### end Alembic commands ###
