"""add index in table products

Revision ID: 2fbea56688f1
Revises: bed7a0d401d0
Create Date: 2025-12-10 09:53:13.758046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbea56688f1'
down_revision: Union[str, Sequence[str], None] = 'bed7a0d401d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_product_product_name', 'products', ['product_name'], unique=False)
    op.create_index('idx_product_sku', 'products', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_sku', table_name='products')
    op.drop_index('idx_product_product_name', table_name='products')
    # ### end Alembic commands ###
