"""fix relasions

Revision ID: 2fca563e6ffc
Revises: 7850a2ff68e1
Create Date: 2025-12-18 13:08:04.545522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fca563e6ffc'
down_revision: Union[str, Sequence[str], None] = '7850a2ff68e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manage_users', sa.Column('branch_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('idx_manage_user_department'), table_name='manage_users')
    op.create_index('idx_manage_user_branch_id', 'manage_users', ['branch_id'], unique=False)
    op.create_index('idx_manage_user_department_id', 'manage_users', ['department_id'], unique=False)
    op.create_foreign_key(None, 'manage_users', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manage_users', type_='foreignkey')
    op.drop_index('idx_manage_user_department_id', table_name='manage_users')
    op.drop_index('idx_manage_user_branch_id', table_name='manage_users')
    op.create_index(op.f('idx_manage_user_department'), 'manage_users', ['department_id'], unique=False)
    op.drop_column('manage_users', 'branch_id')
    # ### end Alembic commands ###
