"""new migration

Revision ID: 4a855c21d554
Revises: e0775de6bc5e
Create Date: 2025-12-21 04:57:53.410998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a855c21d554'
down_revision: Union[str, Sequence[str], None] = 'e0775de6bc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branches', 'department',
               existing_type=postgresql.ENUM('MARKETING', 'SALES', 'FINANCE', 'HR', name='department_enum'),
               type_=sa.Enum('Marketing', 'Sales', 'Engineering', 'Human_Resources', 'Customer_Support', name='department_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branches', 'department',
               existing_type=sa.Enum('Marketing', 'Sales', 'Engineering', 'Human_Resources', 'Customer_Support', name='department_enum', native_enum=False),
               type_=postgresql.ENUM('MARKETING', 'SALES', 'FINANCE', 'HR', name='department_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
