"""update contact

Revision ID: 5418365b41f6
Revises: 4f8499030cd8
Create Date: 2025-12-09 07:57:48.787367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5418365b41f6'
down_revision: Union[str, Sequence[str], None] = '4f8499030cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tasks',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['contact_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'task_id')
    )
    op.add_column('contact_tasks', sa.Column('assign_to', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('contact_tasks_assign_to_contact_fkey'), 'contact_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'contact_tasks', 'users', ['assign_to'], ['id'])
    op.drop_column('contact_tasks', 'assign_to_contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_tasks', sa.Column('assign_to_contact', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contact_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('contact_tasks_assign_to_contact_fkey'), 'contact_tasks', 'contacts', ['assign_to_contact'], ['id'])
    op.drop_column('contact_tasks', 'assign_to')
    op.drop_table('user_tasks')
    # ### end Alembic commands ###
