"""update quotation tables

Revision ID: 59abba9a4e65
Revises: 2018eb240520
Create Date: 2025-12-16 08:23:59.612853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59abba9a4e65'
down_revision: Union[str, Sequence[str], None] = '2018eb240520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('quotation_status', sa.Enum('Pending', 'Accepted', name='quotation_status_enum', native_enum=False), server_default='Pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'quotation_status')
    # ### end Alembic commands ###
