"""delete field tax rate in products table

Revision ID: 652b88952af6
Revises: dd016aadc6f4
Create Date: 2025-12-14 19:01:19.463135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652b88952af6'
down_revision: Union[str, Sequence[str], None] = 'dd016aadc6f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'office_location',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('products', 'tax_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tax_rate', sa.VARCHAR(length=13), autoincrement=False, nullable=False))
    op.alter_column('leads', 'office_location',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
