"""update quotation tables

Revision ID: 6752e4ac9db9
Revises: 1de340673c02
Create Date: 2025-12-15 22:14:01.470868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6752e4ac9db9'
down_revision: Union[str, Sequence[str], None] = '1de340673c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_items', sa.Column('discount', sa.Integer(), nullable=False))
    op.drop_column('quotation_items', 'subtotal')
    op.add_column('quotations', sa.Column('quotation_number', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'quotation_number')
    op.add_column('quotation_items', sa.Column('subtotal', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
    op.drop_column('quotation_items', 'discount')
    # ### end Alembic commands ###
