"""inital migrations

Revision ID: 78a64f27ab12
Revises: 
Create Date: 2025-12-07 22:07:46.631662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78a64f27ab12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_fullname', 'users', ['fullname'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('company', sa.String(length=30), nullable=False),
    sa.Column('job_title', sa.String(length=30), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('Web Form', 'Whatsapp', 'Manual', name='lead_source_enum', native_enum=False), nullable=False),
    sa.Column('contact', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('New', 'Contacted', 'Qualified', 'Proposal', 'Closed Won', 'Closed Lost', name='lead_status_enum', native_enum=False), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('last_contacted', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_assigned_to', 'leads', ['assigned_to'], unique=False)
    op.create_index('idx_lead_created_at', 'leads', ['created_at'], unique=False)
    op.create_index('idx_lead_source', 'leads', ['source'], unique=False)
    op.create_index('idx_lead_status', 'leads', ['status'], unique=False)
    op.create_table('contact_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=255), nullable=False),
    sa.Column('assign_to_contact', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assign_to_contact'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_tasks')
    op.drop_table('contact_notes')
    op.drop_index('idx_lead_status', table_name='leads')
    op.drop_index('idx_lead_source', table_name='leads')
    op.drop_index('idx_lead_created_at', table_name='leads')
    op.drop_index('idx_lead_assigned_to', table_name='leads')
    op.drop_table('leads')
    op.drop_table('contacts')
    op.drop_index('idx_user_fullname', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
