"""update field pipelines

Revision ID: 78d0a57fc049
Revises: 2fbea56688f1
Create Date: 2025-12-10 17:27:09.910557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d0a57fc049'
down_revision: Union[str, Sequence[str], None] = '2fbea56688f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_column('pipelines', 'is_closed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('pipelines', 'is_deleted')
    # ### end Alembic commands ###
