"""make manage_user nullable on create

Revision ID: 8cf7b20385fd
Revises: bc8317ad4bf5
Create Date: 2025-12-18 18:34:45.076545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf7b20385fd'
down_revision: Union[str, Sequence[str], None] = 'bc8317ad4bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manage_users', 'department_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('manage_users', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manage_users', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('manage_users', 'department_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
