"""update table pipelines

Revision ID: 9b09e4780858
Revises: 1e8c6e9686cb
Create Date: 2025-12-14 11:45:38.273427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b09e4780858'
down_revision: Union[str, Sequence[str], None] = '1e8c6e9686cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('assigned_to', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'pipelines', 'users', ['assigned_to'], ['id'])
    op.alter_column('quotation_items', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotation_items', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.drop_column('pipelines', 'assigned_to')
    # ### end Alembic commands ###
