"""initial migrations

Revision ID: a72fd4881ab0
Revises: 
Create Date: 2025-12-19 16:31:55.352635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72fd4881ab0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('job_title', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sku', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_product_name', 'products', ['product_name'], unique=False)
    op.create_index('idx_product_sku', 'products', ['sku'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('permission_name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_name', sa.String(length=20), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['role_permissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Enum('Business Owner', 'C-Level', 'Senior Manager', 'Staff', 'Lainnya', name='user_position_enum', native_enum=False), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('avatar_initial', sa.String(length=2), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('role', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['user_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_fullname', 'users', ['fullname'], unique=False)
    op.create_table('contact_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.String(length=255), nullable=False),
    sa.Column('assign_to', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assign_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('industry', sa.Enum('Manufaktur', 'Teknologi', 'Ritel', 'Finance', name='lead_industry_enum', native_enum=False), nullable=False),
    sa.Column('company_size', sa.Enum('1 - 50 Karyawan', '51 - 200 Karyawan', '201+ Karyawan', name='lead_company_size_enum', native_enum=False), nullable=False),
    sa.Column('office_location', sa.String(length=255), nullable=False),
    sa.Column('lead_status', sa.Enum('New', 'Contacted', 'Qualified', 'Proposal', 'Closed - Won', 'Closed - Lost', name='lead_status_enum', native_enum=False), nullable=False),
    sa.Column('lead_source', sa.Enum('Web Form', 'WhatsApp', 'Manual Entry', name='lead_source_enum', native_enum=False), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('tag', sa.Enum('Renewal', 'Urgent', 'High Value', 'Trial User', name='lead_tag_enum', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_assigned_to', 'leads', ['assigned_to'], unique=False)
    op.create_index('idx_lead_created_at', 'leads', ['created_at'], unique=False)
    op.create_index('idx_lead_source', 'leads', ['lead_source'], unique=False)
    op.create_index('idx_lead_status', 'leads', ['lead_status'], unique=False)
    op.create_table('mailings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('send_date', sa.Date(), nullable=False),
    sa.Column('statistic', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('reminder_date', sa.Date(), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipelines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deal_name', sa.String(length=255), nullable=False),
    sa.Column('client_account', sa.Uuid(), nullable=False),
    sa.Column('deal_stage', sa.Enum('Prospect', 'Qualified', 'Negotiation', 'Proposal', 'Closed - Won', 'Closed - Lost', name='pipeline_deal_stage', native_enum=False), nullable=False),
    sa.Column('expected_close_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('probability_of_close', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('probability_of_close >= 0 AND probability_of_close <= 100'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_account'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('skype', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_otps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('otp_type', sa.Enum('Verification Email', 'Reset Password', name='user_otp_type_enum', native_enum=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text("now() + interval '10 minutes'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('quotation_number', sa.String(length=10), nullable=False),
    sa.Column('quotation_title', sa.String(length=255), nullable=False),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quotation_status', sa.Enum('Pending', 'Accepted', name='quotation_status_enum', native_enum=False), server_default='Pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotation_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotation_items')
    op.drop_table('quotations')
    op.drop_table('user_otps')
    op.drop_table('user_details')
    op.drop_table('pipelines')
    op.drop_table('notes')
    op.drop_table('mailings')
    op.drop_index('idx_lead_status', table_name='leads')
    op.drop_index('idx_lead_source', table_name='leads')
    op.drop_index('idx_lead_created_at', table_name='leads')
    op.drop_index('idx_lead_assigned_to', table_name='leads')
    op.drop_table('leads')
    op.drop_table('contact_tasks')
    op.drop_table('contact_notes')
    op.drop_index('idx_user_fullname', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index('idx_product_sku', table_name='products')
    op.drop_index('idx_product_product_name', table_name='products')
    op.drop_table('products')
    op.drop_table('contacts')
    # ### end Alembic commands ###
