"""create pipeline table

Revision ID: abe71c06e5d3
Revises: c657c520b2a6
Create Date: 2025-12-06 09:00:34.740662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe71c06e5d3'
down_revision: Union[str, Sequence[str], None] = 'c657c520b2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deal_name', sa.String(length=255), nullable=False),
    sa.Column('client_account', sa.String(length=255), nullable=False),
    sa.Column('deal_stage', sa.Enum('Prospect', 'Qualified', 'Negotiation', 'Proposal', name='pipeline_deal_stage', native_enum=False), nullable=False),
    sa.Column('expected_close_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('probability_of_close', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('probability_of_close >= 0 AND probability_of_close <= 100'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipelines')
    # ### end Alembic commands ###
