"""fix department and branch

Revision ID: bc8317ad4bf5
Revises: 2fca563e6ffc
Create Date: 2025-12-18 14:33:04.601165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8317ad4bf5'
down_revision: Union[str, Sequence[str], None] = '2fca563e6ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'name',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('departments_name_key'), 'departments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('departments_name_key'), 'departments', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('departments', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
