"""initial migrations

Revision ID: c657c520b2a6
Revises: 
Create Date: 2025-12-04 05:38:37.670867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c657c520b2a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('Sales', 'Admin', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_fullname', 'users', ['fullname'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('Web Form', 'Whatsapp', 'Manual', name='lead_source_enum', native_enum=False), nullable=False),
    sa.Column('contact', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('New', 'Contacted', 'Qualified', 'Proposal', 'Closed Won', 'Closed Lost', name='lead_status_enum', native_enum=False), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('last_contacted', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_assigned_to', 'leads', ['assigned_to'], unique=False)
    op.create_index('idx_lead_created_at', 'leads', ['created_at'], unique=False)
    op.create_index('idx_lead_source', 'leads', ['source'], unique=False)
    op.create_index('idx_lead_status', 'leads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lead_status', table_name='leads')
    op.drop_index('idx_lead_source', table_name='leads')
    op.drop_index('idx_lead_created_at', table_name='leads')
    op.drop_index('idx_lead_assigned_to', table_name='leads')
    op.drop_table('leads')
    op.drop_index('idx_user_fullname', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
