"""rename lead_name to contact_id in leads table

Revision ID: dd016aadc6f4
Revises: 9b09e4780858
Create Date: 2025-12-14 16:25:35.066316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd016aadc6f4'
down_revision: Union[str, Sequence[str], None] = '9b09e4780858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('contact_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('leads_lead_name_fkey'), 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'contacts', ['contact_id'], ['id'])
    op.drop_column('leads', 'lead_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('lead_name', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key(op.f('leads_lead_name_fkey'), 'leads', 'contacts', ['lead_name'], ['id'])
    op.drop_column('leads', 'contact_id')
    # ### end Alembic commands ###
