from .auth import router as auth_router
from .contacts import router as contacts_router
from .userprofile import router as userprofile_router
from .leads import router as leads_router
from .pipelines import router as pipelines_router
from .products import router as products_router
from .quotations import router as quotations_router
from .users import router as users_router
from .mailings import router as mailings_router
from .userdevice import router as userdevice_router
