from .lead_repository import LeadRepository
from .manage_user_repository import ManageUserRepository
from .permission_repository import PermissionRepository
from .pipeline_repository import PipelineRepository
from .product_repository import ProductRepository
from .quotation_repository import QuotationRepository
from .role_repository import RoleRepository
from .user_repository import UserRepository
